### ISSUE TITLE
L

### ISSUE THREAD

**Issue by gotty2001** [github/codespaces-jupyter#30]
P

**Comment by Molecule24** [comment]
Sorry for that.. faced some technical issue sir... 17:12, 4 February 2023, gotty2001 ***@***.***>:
Closed #30 as not planned.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile
